### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by fediachov** [SevenbytesSoftware/SevenConverter#1]
- [ ] UI for console output with parsing of errors 
- [ ] progress bar
- [ ] working file info
- [ ] convert CD/DVD

**Comment by heckez-sys** [comment]
webm support?

**Comment by fediachov** [comment]
> 
> 
> webm support?

Hi, 
Thanks for request. I have added feature in the road map.

**Comment by fediachov** [comment]
> 
> 
> webm support?

I will add it in Seven Converter in next build (few days)

**Comment by nhan000** [comment]
Feature request: 

- Convert video to audio file 
- Video to audio file using a static image

**Comment by jonatino** [comment]
are conversions lossless? I’d like to convert old avi videos to mp4 but want to retain as much audio and video quality as possible.

**Comment by Antxj** [comment]
Support  to AAC audio codec :)

**Comment by DealsBeam** [comment]
Can you please support converting to mp3 output
